### ISSUE TITLE
Main npdm

### ISSUE THREAD

**Issue by Pologx** [javilobo8/XCI2TitleConverter#14]
Hello I have this problem when I preapare a game.

![image](https://user-images.githubusercontent.com/38161366/41824388-357d0aa4-77dd-11e8-9c83-a73a24dc7401.png)
![image](https://user-images.githubusercontent.com/38161366/41824392-47cf0e32-77dd-11e8-9a68-b26ad6666eb9.png)

**Comment by Pologx** [comment]
![image](https://user-images.githubusercontent.com/38161366/41824483-d1e833c2-77de-11e8-9a2f-d0efab9f8ae3.png)

**Comment by Pologx** [comment]
![image](https://user-images.githubusercontent.com/38161366/41824486-e51f54ac-77de-11e8-8b5c-9869d7989b5c.png)

**Comment by javilobo8** [comment]
You don't have all the keys in keys.txt or you are trying to convert a type-2 cart.
