### ISSUE TITLE
Suggestion: Using threads.

### ISSUE THREAD

**Issue by NaamloosDT** [javilobo8/XCI2TitleConverter#6]
At the moment the programs hangs when your `StartProcess()` method is called. It is recommended to run long running code like this in a thread, as running blocking code on UI threads is considered bad practice.

What you could do is disable the start button on your UI until the method is done running.

Other than that, thanks for your contribution to the scene. Great job making this. Keep the good work up c:

**Comment by NaamloosDT** [comment]
Also, I might consider contributing later on c:

**Comment by javilobo8** [comment]
Ok, I promise that I will execute hactool processes in diferent threads, I'm not so much familiarized with Windows Applications, so this kind of things will teach me to improove :)

Thank you, I'll keep the issue open until I implement it.

:)

**Comment by javilobo8** [comment]
WIP: https://github.com/javilobo8/XCI2TitleConverter/pull/7
